services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  gift-asm:
    build:
      context: ./asm
      dockerfile: Dockerfile
    container_name: gift-asm
    depends_on:
      - ollama
    stdin_open: true

volumes:
  ollama_data: